In [29]:
##########################################################################################################################
# INTRODUCTION TO SCI-KIT LEARN
##########################################################################################################################
# You have been provided with a dataset that contains the costs of advertising on different media channels
# - and - 
# the corresponding sales of XYZ firm. Evaluate the dataset to:
#
# 1) Find the features or media channels used by the firm.
# 2) Find the sales figures for each channel.
# 3) Create a model to predict the sales outcome.
# 4) Split it into training and testing datasets for the model.
# 5) Calculate the mean squared error (MSE).
##########################################################################################################################

In [43]:
# [Import the required libraries]
import pandas as pd
import sklearn as skl

In [44]:
# [Import the advertising dataset]
df_adv_data = pd.read_csv('//Users//adityasaxena//Desktop//MyProjects//Data_Science_with_Python//Introduction to Scikit-Learn//Advertising.csv',index_col = 0)

In [45]:
# [View the top 5 records]
df_adv_data.head()

TV  Radio  Newspaper  Sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [46]:
# [View the dataset size]
df_adv_data.size

800

In [47]:
# [View the shape of the dataset]
df_adv_data.shape

(200, 4)

In [35]:
# [View the columns of the dataset]
df_adv_data.columns

Index(['TV', 'Radio', 'Newspaper', 'Sales'], dtype='object')

In [36]:
# [Create a feature object from the columns]
X_Feature = df_adv_data[['Newspaper','Radio','TV']]

In [37]:
# [View feature object]
X_Feature.head()

Newspaper  Radio     TV
1       69.2   37.8  230.1
2       45.1   39.3   44.5
3       69.3   45.9   17.2
4       58.5   41.3  151.5
5       58.4   10.8  180.8

In [38]:
# [Create target object from sales column which is a response in the dataset]
Y_Target = df_adv_data[['Sales']]

In [39]:
# [View the target object]
Y_Target.head()

Sales
1   22.1
2   10.4
3    9.3
4   18.5
5   12.9

In [40]:
# [View the shape of the feature object]
X_Feature.shape

(200, 3)

In [41]:
# [View the shape of the target object]
Y_Target.shape

(200, 1)

In [51]:
# [Split Test and Training Data]
# by default 75% training data and 25% testing data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X_Feature, Y_Target, random_state = 1)

In [53]:
# [View shape of x_train]
x_train.shape

(150, 3)

In [54]:
# [View shape of x_test]
x_test.shape

(50, 3)

In [55]:
# [View shape of y_train]
y_train.shape

(150, 1)

In [57]:
# [View shape of y_test]
y_test.shape

(50, 1)

In [59]:
# [Import the linear regression model]
from sklearn.linear_model import LinearRegression

In [60]:
# [Creating a linear regression object]
linreg = LinearRegression()

In [61]:
# [Training the linreg]
linreg.fit(x_train,y_train)

LinearRegression()

In [63]:
# [Printing the linreg intercept]
linreg.intercept_

array([2.87696662])

In [64]:
# [Printing the linreg coefficient]
linreg.coef_

array([[0.00345046, 0.17915812, 0.04656457]])

In [83]:
# [Prediction]
y_pred = linreg.predict(x_test)

In [84]:
# [Pringing the Predicted Values]
print(y_pred)

[[21.70910292]
 [16.41055243]
 [ 7.60955058]
 [17.80769552]
 [18.6146359 ]
 [23.83573998]
 [16.32488681]
 [13.43225536]
 [ 9.17173403]
 [17.333853  ]
 [14.44479482]
 [ 9.83511973]
 [17.18797614]
 [16.73086831]
 [15.05529391]
 [15.61434433]
 [12.42541574]
 [17.17716376]
 [11.08827566]
 [18.00537501]
 [ 9.28438889]
 [12.98458458]
 [ 8.79950614]
 [10.42382499]
 [11.3846456 ]
 [14.98082512]
 [ 9.78853268]
 [19.39643187]
 [18.18099936]
 [17.12807566]
 [21.54670213]
 [14.69809481]
 [16.24641438]
 [12.32114579]
 [19.92422501]
 [15.32498602]
 [13.88726522]
 [10.03162255]
 [20.93105915]
 [ 7.44936831]
 [ 3.64695761]
 [ 7.22020178]
 [ 5.9962782 ]
 [18.43381853]
 [ 8.39408045]
 [14.08371047]
 [15.02195699]
 [20.35836418]
 [20.57036347]
 [19.60636679]]


In [91]:
# [Importing the libraries to calculate the mean squared error]
from sklearn import metrics
import numpy as np

In [93]:
# [Calculating the mean squared error]
from sklearn.metrics import mean_squared_error

rms = np.sqrt(mean_squared_error(y_test, y_pred, squared=False))

In [95]:
# [Displaying the value of rms]
rms

1.1851799116728623