In [89]:
## [AN INTRODUCTORY NOTEBOOK ON NUMPY]
## @author  : Aditya Saxena
## @date    : August 22, 2022
## @version : 1.0

# [CHAPTER 1] - Introduction to Shape Manipulation in Numpy
print("INTRODUCTION TO SHAPE MANIPULATION IN NUMPY")

INTRODUCTION TO SHAPE MANIPULATION IN NUMPY


In [96]:
# [Importing the Numpy Library]
import numpy as np
temprature_in_toronto = np.array([[23,25,28,30,35,29,28],[26,25,28,30,33,29,27],[27,26,23,21,18,20,25],[22,20,26,29,33,31,30]])

In [152]:
# [Reshaping the Array 4x7]
temprature_in_toronto.reshape(4,7)

array([[23, 25, 28, 30, 35, 29, 28],
       [26, 25, 28, 30, 33, 29, 27],
       [27, 26, 23, 21, 18, 20, 25],
       [22, 20, 26, 29, 33, 31, 30]])

In [153]:
# [Reshaping the Array 7x4]
temprature_in_toronto.reshape(7,4)

array([[23, 25, 28, 30],
       [35, 29, 28, 26],
       [25, 28, 30, 33],
       [29, 27, 27, 26],
       [23, 21, 18, 20],
       [25, 22, 20, 26],
       [29, 33, 31, 30]])

In [154]:
# [Reshaping the Array 7x2x2]
temprature_in_toronto.reshape(7,2,2)

array([[[23, 25],
        [28, 30]],

       [[35, 29],
        [28, 26]],

       [[25, 28],
        [30, 33]],

       [[29, 27],
        [27, 26]],

       [[23, 21],
        [18, 20]],

       [[25, 22],
        [20, 26]],

       [[29, 33],
        [31, 30]]])

In [258]:
# [Reshaping the Array back to 7x4]
ravel_array = temprature_in_toronto.reshape(7,4)
print(ravel_array)

[[23 25 28 30]
 [35 29 28 26]
 [25 28 30 33]
 [29 27 27 26]
 [23 21 18 20]
 [25 22 20 26]
 [29 33 31 30]]


In [156]:
# [Splitting the Array 7 equal parts]
np.hsplit(temprature_in_toronto,7)

[array([[23],
        [26],
        [27],
        [22]]),
 array([[25],
        [25],
        [26],
        [20]]),
 array([[28],
        [28],
        [23],
        [26]]),
 array([[30],
        [30],
        [21],
        [29]]),
 array([[35],
        [33],
        [18],
        [33]]),
 array([[29],
        [29],
        [20],
        [31]]),
 array([[28],
        [27],
        [25],
        [30]])]

In [157]:
# [Creating an Array - 1]
humidity_in_toronto_1 = np.array([34,73,34,45,56,70,90])

In [158]:
# [Creating an Array - 2]
humidity_in_toronto_2 = np.array([55,57,70,43,44,87,56])

In [159]:
# [Creating an Array - 3]
humidity_in_toronto_3 = np.array([54,33,21,93,34,67,59])

In [160]:
# [Creating an Array - 4]
humidity_in_toronto_4 = np.array([10,63,23,48,50,90,13])

In [248]:
# [Putting the humidity arrays together as a single array]
np.hstack((humidity_in_toronto_1, humidity_in_toronto_2, humidity_in_toronto_3, humidity_in_toronto_4))

array([34, 73, 34, 45, 56, 70, 90, 55, 57, 70, 43, 44, 87, 56, 54, 33, 21,
       93, 34, 67, 59, 10, 63, 23, 48, 50, 90, 13])

In [249]:
# [Chapter 2 - Introduction to Universal Functions]
print("INTRODUCTION TO UNIVERSAL FUNCTIONS")

INTRODUCTION TO UNIVERSAL FUNCTIONS


In [250]:
# [Introduction to Trigonometric Functions]

# To use trigonometric functions in Numpy we import pi from Numpy
from numpy import pi

print("Value of Pi = " + str(pi))

Value of Pi = 3.141592653589793


In [251]:
# [Printing various values COS Function]
print("COS(0)    = " + str(np.cos(0)))
print("COS(pi)   = " + str(np.cos(pi)))
print("COS(pi/2) = " + str(np.cos(pi/2)))

COS(0)    = 1.0
COS(pi)   = -1.0
COS(pi/2) = 6.123233995736766e-17


In [252]:
# [Printing various valus of SIN Function]
print("SIN(pi/2)  = " + str(np.sin(pi/2)))
print("SIN(3pi/2) = " + str(np.sin(pi*(3/2))))
print("SIN(pi)    = " + str(np.sin(pi)))

SIN(pi/2)  = 1.0
SIN(3pi/2) = -1.0
SIN(pi)    = 1.2246467991473532e-16


In [254]:
# Printing Value of Sin^2(num) + Cos^2(num)
input_num = int(input("Please input a number of degrees : "))
sin_of_num_of_degrees = np.sin((pi/180)*input_num)**2
print ("SIN of "+str(input_num)+" DEGREES : "+str(sin_of_num_of_degrees))
cos_of_num_of_degrees = np.cos((pi/180)*input_num)**2
print ("COS of "+str(input_num)+" DEGREES : "+str(cos_of_num_of_degrees))
sum_of_squares_of_sin_and_cos = sin_of_num_of_degrees + cos_of_num_of_degrees
print("SUM OF SQUARES OF SIN AND COS : "+str(sum_of_squares_of_sin_and_cos))

Please input a number of degrees :  33


SIN of 33 DEGREES : 0.2966316784620999
COS of 33 DEGREES : 0.7033683215379002
SUM OF SQUARES OF SIN AND COS : 1.0


In [259]:
# [Use of Ravel Function]
# A 1-D array, containing the elements of the input, is returned. A copy is made only if needed.
temprature_in_toronto.ravel()

array([23, 25, 28, 30, 35, 29, 28, 26, 25, 28, 30, 33, 29, 27, 27, 26, 23,
       21, 18, 20, 25, 22, 20, 26, 29, 33, 31, 30])

In [242]:
# [Finding Square Root of Elements in an Array]
sqrt_humidity_in_toronto_1 = np.sqrt(humidity_in_toronto_1)
print(sqrt_humidity_in_toronto_1)

[5.83095189 8.54400375 5.83095189 6.70820393 7.48331477 8.36660027
 9.48683298]


In [68]:
# [Using the Floor Function on an Array]
floor_sqrt_humidity_in_toronto = np.floor(np.sqrt(humidity_in_toronto_1))

In [184]:
# [Using the print function to print an array]
print(floor_sqrt_humidity_in_toronto)

[5. 8. 5. 6. 7. 8. 9.]


In [187]:
# [Using the Exponent Function on an Array]
exp_floor_sqrt_humidity_in_toronto = np.exp(floor_sqrt_humidity_in_toronto)

In [189]:
# [Printing an Array without the Print Function]
exp_floor_sqrt_humidity_in_toronto

array([ 148.4131591 , 2980.95798704,  148.4131591 ,  403.42879349,
       1096.63315843, 2980.95798704, 8103.08392758])

In [190]:
# [Demonstrating other Numpy Functions]
print("[DEMO] NUMPY FUNCTIONS DEMO")

[DEMO] NUMPY FUNCTIONS DEMO


In [191]:
# [Defining a new ndarray in Numpy]
new_array = np.array([10,20,30,40,50,60,70,80,90,100,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [192]:
# [Printing the array without print function]
new_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100,   1,   2,   3,
         4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15])

In [193]:
# [Using the print function to print an array]
print(new_array)

[ 10  20  30  40  50  60  70  80  90 100   1   2   3   4   5   6   7   8
   9  10  11  12  13  14  15]


In [194]:
# [Creating a 3x3 array with Numpy Zeros Function]
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [195]:
# [Using the print function to print an array]
print(array_with_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [197]:
# [Creating an 8x8 array with Numpy One's Function]
array_with_ones_8x8 = np.ones((8,8))
print(array_with_ones_8x8)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [198]:
# [Creating an 3x3 array with Numpy One's Function]
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [200]:
# [Creating an array with Numpy Empty Function]
array_with_empty = np.empty((2,3))
print(array_with_empty)

[[0.00e+000 1.53e-322 0.00e+000]
 [0.00e+000 0.00e+000 0.00e+000]]


In [208]:
# [Creating an array with Numpy Arrange Method]
array_with_arange = np.arange(20)
print(array_with_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [209]:
# [Reshape Method to change/create array]
array_with_arange.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [210]:
# [Reshape Method to change/create array]
array_with_arange.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [216]:
# [Reshape Method to change/create array]
array_with_arange.reshape(1,2,2,5)

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]]])

In [238]:
# [Linspace for linearly (equally) spaced data elements]
# Return evenly spaced numbers over a specified interval.
np_linspace = np.linspace(0,10,11)
print(np_linspace)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [235]:
# [One Dimensional Array]
np_one_dim_array = np.array([1,2,3,4])
print(np_one_dim_array)

[1 2 3 4]


In [227]:
# [Two Dimensional Array]
np_two_dim_array = np.array([[1,2,3,4],[5,6,7,8]])
print(np_two_dim_array)

[[1 2 3 4]
 [5 6 7 8]]


In [229]:
# [Three Dimensional Array]
np_three_dim_array = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,17]],[[19,20,21],[22,23,24],[25,26,27]]])
print(np_three_dim_array)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 17]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


In [240]:
# [Reshaping a three dimensional array]
reshape_three_dim_as_one = np_three_dim_array.reshape(1,27)
print(reshape_three_dim_as_one)

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 17 19 20 21 22 23 24
  25 26 27]]


In [261]:
# [Resizing an Array]
reshape_three_dim_as_one.resize(2,7)

ValueError: cannot resize this array: it does not own its data

In [268]:
# [Resizing an Array]
resizable_array = np.array([1,2,3,4,5,6,7,8,9,10])
print(resizable_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [269]:
resizable_array.resize(2,5)
print(resizable_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
